# Generated by Django 2.2.10 on 2020-02-18 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
