# Generated by Django 2.2.10 on 2020-02-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200218_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='apply_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='is_easy_apply',
            field=models.BooleanField(default=False),
        ),
    ]
