# Generated by Django 2.2.10 on 2020-02-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200218_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
