# Generated by Django 2.2.10 on 2020-02-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobsite_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsite',
            name='is_applied',
        ),
        migrations.AddField(
            model_name='job',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_site',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='keywords',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
