# Generated by Django 2.2.10 on 2020-02-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200219_0917'),
        ('jobs', '0011_auto_20200218_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='resume.Resume'),
        ),
    ]
