# Generated by Django 2.2.10 on 2020-03-04 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('RE', 'Resume'), ('CL', 'Cover Letter')], default='RE', max_length=64),
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('output_format', models.CharField(choices=[('HTML', 'HTML'), ('JSON', 'JSON'), ('DOCX', 'DOCX'), ('PDF', 'PDF')], default='JSON', max_length=64)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Applicant')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Template')),
            ],
        ),
    ]
